spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-chrishi-dev
---    
spring:
  profiles: test #测试环境
  application: 
  name: microservicecloud-config-chrishi-test
  
 #保存格式必须为utf-8